# This tells Netlify how to build your site.
[build]
  command = "npm run build"
  publish = "dist"

# This tells Netlify where your serverless functions are.
[functions]
  directory = "api"

# This is the critical rule to fix the 404 error.
# It forwards requests from your app's /api/ path
# to the actual function on Netlify's backend.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
